export 'package:proyectoprogramovil/pages/auth_page.dart';
export 'package:proyectoprogramovil/pages/main_auth_guard.dart';
export 'package:proyectoprogramovil/pages/customers_page.dart';
export 'package:proyectoprogramovil/pages/home_page.dart';
export 'package:proyectoprogramovil/pages/profile_page.dart';
export 'package:proyectoprogramovil/pages/services_page.dart';
export 'package:proyectoprogramovil/pages/main_page.dart';
export 'package:proyectoprogramovil/pages/login_page.dart';
export 'package:proyectoprogramovil/pages/register_page.dart';
