// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdnytpK2ldCeGG2mRPIXii7fcszep7vJo',
    appId: '1:227380616431:web:b54a317c823474a28e8f1a',
    messagingSenderId: '227380616431',
    projectId: 'app-taller-pm',
    authDomain: 'app-taller-pm.firebaseapp.com',
    storageBucket: 'app-taller-pm.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeMRIH_lbzhOHskwx_6DzwP9M74-c_ezI',
    appId: '1:227380616431:android:c3f1a4ca3a9473cd8e8f1a',
    messagingSenderId: '227380616431',
    projectId: 'app-taller-pm',
    storageBucket: 'app-taller-pm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaHAhXuY5HOCwkHk07sT2MyQvHH3VZoak',
    appId: '1:227380616431:ios:af1d99e533c6d09a8e8f1a',
    messagingSenderId: '227380616431',
    projectId: 'app-taller-pm',
    storageBucket: 'app-taller-pm.firebasestorage.app',
    iosBundleId: 'com.example.proyectoprogramovil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaHAhXuY5HOCwkHk07sT2MyQvHH3VZoak',
    appId: '1:227380616431:ios:af1d99e533c6d09a8e8f1a',
    messagingSenderId: '227380616431',
    projectId: 'app-taller-pm',
    storageBucket: 'app-taller-pm.firebasestorage.app',
    iosBundleId: 'com.example.proyectoprogramovil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdnytpK2ldCeGG2mRPIXii7fcszep7vJo',
    appId: '1:227380616431:web:3c80c1d5f6e649978e8f1a',
    messagingSenderId: '227380616431',
    projectId: 'app-taller-pm',
    authDomain: 'app-taller-pm.firebaseapp.com',
    storageBucket: 'app-taller-pm.firebasestorage.app',
  );
}
